### ISSUE TITLE
Style Missing

### ISSUE THREAD

**Issue by pranav801** [Fawaskp/Auto-Search-Bing#1]
I have identified a missing CSS file in the Auto-Seach-Bing repository. The CSS file, named style.css, appears to be absent from the repository, and this is causing styling problems, broken layout.

I recommend that we add the missing CSS file to the repository to address the issue. I am willing to provide the file and create a pull request if that would be helpful.

Here I attaching the screen short for detailing the issue ;

![Screenshot from 2023-11-07 09-19-58](https://github.com/Fawaskp/Auto-Search-Bing/assets/119454239/e15e88cd-02dc-4ea9-bed8-2106ede14455)

**Comment by Fawaskp** [comment]
Thank you for reporting this issue, resolved 👍
